name: SWAIF Feature
description: Factory Input Package for stage-gated SWAIF execution
title: "[SWAIF] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Submit a SWAIF Factory Input Package. Required headings are parsed by automation.
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug
      description: "Use kebab-case. Example: 001-clinic-billing"
      placeholder: 001-example-feature
    validations:
      required: true
  - type: dropdown
    id: declared_execution_type
    attributes:
      label: Declared Execution Type
      options:
        - Hands-On Run
        - Research Experiment
        - Prototype
        - PoC
        - MVP
        - Scaled Product
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Summarize the feature and desired outcome.
      placeholder: Describe what this feature is and why it matters.
    validations:
      required: true
  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the pain/problem this work solves.
      placeholder: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: List what is in scope for this feature.
      value: |
        - In-scope item 1
        - In-scope item 2
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Use measurable checklist items with AC IDs.
      value: |
        - [ ] AC-001 Measurable expected outcome
        - [ ] AC-002 Measurable expected outcome
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: List technical, timeline, compliance, or dependency constraints.
      value: |
        - Constraint 1
        - Constraint 2
    validations:
      required: true
  - type: textarea
    id: non_goals
    attributes:
      label: Non-Goals
      description: Explicitly list what is out of scope.
      value: |
        - Out-of-scope item 1
        - Out-of-scope item 2
    validations:
      required: true
  - type: textarea
    id: implementation_hints
    attributes:
      label: Implementation Hints (optional)
      description: Optional references, docs, or technical pointers.
      placeholder: Helpful references or implementation notes.
    validations:
      required: false
